volumes:
  firefox:

services:
  firefox:
    image: ghcr.io/linuxserver/firefox
    container_name: firefox
    environment:
      - PUID=1000 #change this to for your settings
      - PGID=1000 #change this to for your settings
      - TZ=Europe/Athens  #change this to for your location
    volumes:
      - /portainer/Files/AppData/Config/firefox:/config
    ports:
      - 3456:3000
    shm_size: "1gb"
    
